In [16]:
## Importing libraries
import boto3
import pandas as pd
import numpy as np
import miceforest as mf

## -------------------------------------------

## Sanity check
print('-- Process Starting --')

## Defining the bucket
s3 = boto3.resource('s3')
bucket_name = 'evan-callaghan-bucket'
bucket = s3.Bucket(bucket_name)

file_key = 'Kaggle-American-Express-Default/amex_train_data.csv'
file_key2 = 'Kaggle-American-Express-Default/amex_train_labels.csv'

bucket_object = bucket.Object(file_key)
bucket_object2 = bucket.Object(file_key2)

file_object = bucket_object.get()
file_object2 = bucket_object2.get()

file_content_stream = file_object.get('Body')
file_content_stream2 = file_object2.get('Body')

## Creating data-type dictionary for reading the train data-frame
dtype_dict = {'customer_ID': "object", 'S_2': "object", 'P_2': 'float16', 'D_39': 'float16', 'B_1': 'float16','B_2': 'float16', 'R_1': 'float16','S_3': 'float16','D_41': 'float16','B_3': 'float16','D_42': 'float16','D_43': 'float16','D_44': 'float16', 'B_4': 'float16','D_45': 'float16','B_5': 'float16','R_2': 'float16','D_46': 'float16','D_47': 'float16','D_48': 'float16', 'D_49': 'float16','B_6': 'float16','B_7': 'float16','B_8': 'float16','D_50': 'float16','D_51': 'float16','B_9': 'float16', 'R_3': 'float16','D_52': 'float16','P_3': 'float16','B_10': 'float16','D_53': 'float16','S_5': 'float16','B_11': 'float16', 'S_6': 'float16','D_54': 'float16','R_4': 'float16','S_7': 'float16','B_12': 'float16','S_8': 'float16','D_55': 'float16', 'D_56': 'float16','B_13': 'float16','R_5': 'float16','D_58': 'float16','S_9': 'float16','B_14': 'float16','D_59': 'float16', 'D_60': 'float16','D_61': 'float16','B_15': 'float16','S_11': 'float16','D_62': 'float16','D_63': 'object','D_64': 'object', 'D_65': 'float16','B_16': 'float16','B_17': 'float16','B_18': 'float16','B_19': 'float16','D_66': 'float16','B_20': 'float16', 'D_68': 'float16','S_12': 'float16','R_6': 'float16','S_13': 'float16','B_21': 'float16','D_69': 'float16','B_22': 'float16', 'D_70': 'float16','D_71': 'float16','D_72': 'float16','S_15': 'float16','B_23': 'float16','D_73': 'float16','P_4': 'float16', 'D_74': 'float16','D_75': 'float16','D_76': 'float16','B_24': 'float16','R_7': 'float16','D_77': 'float16','B_25': 'float16', 'B_26': 'float16','D_78': 'float16','D_79': 'float16','R_8': 'float16','R_9': 'float16','S_16': 'float16','D_80': 'float16', 'R_10': 'float16','R_11': 'float16','B_27': 'float16','D_81': 'float16','D_82': 'float16','S_17': 'float16','R_12': 'float16', 'B_28': 'float16','R_13': 'float16','D_83': 'float16','R_14': 'float16','R_15': 'float16','D_84': 'float16','R_16': 'float16', 'B_29': 'float16','B_30': 'float16','S_18': 'float16','D_86': 'float16','D_87': 'float16','R_17': 'float16','R_18': 'float16', 'D_88': 'float16','B_31': 'int64','S_19': 'float16','R_19': 'float16','B_32': 'float16','S_20': 'float16','R_20': 'float16', 'R_21': 'float16','B_33': 'float16','D_89': 'float16','R_22': 'float16','R_23': 'float16','D_91': 'float16','D_92': 'float16', 'D_93': 'float16','D_94': 'float16','R_24': 'float16','R_25': 'float16','D_96': 'float16','S_22': 'float16','S_23': 'float16', 'S_24': 'float16','S_25': 'float16','S_26': 'float16','D_102': 'float16','D_103': 'float16','D_104': 'float16','D_105': 'float16', 'D_106': 'float16','D_107': 'float16','B_36': 'float16','B_37': 'float16', 'R_26': 'float16','R_27': 'float16','B_38': 'float16', 'D_108': 'float16','D_109': 'float16','D_110': 'float16','D_111': 'float16','B_39': 'float16','D_112': 'float16','B_40': 'float16', 'S_27': 'float16','D_113': 'float16','D_114': 'float16','D_115': 'float16','D_116': 'float16','D_117': 'float16','D_118': 'float16', 'D_119': 'float16','D_120': 'float16','D_121': 'float16','D_122': 'float16','D_123': 'float16','D_124': 'float16','D_125': 'float16', 'D_126': 'float16','D_127': 'float16','D_128': 'float16','D_129': 'float16','B_41': 'float16','B_42': 'float16','D_130': 'float16', 'D_131': 'float16','D_132': 'float16','D_133': 'float16','R_28': 'float16','D_134': 'float16','D_135': 'float16','D_136': 'float16', 'D_137': 'float16','D_138': 'float16','D_139': 'float16','D_140': 'float16','D_141': 'float16','D_142': 'float16','D_143': 'float16', 'D_144': 'float16','D_145': 'float16'}

## Reading the data
train = pd.read_csv(file_content_stream, dtype = dtype_dict)
train_labels = pd.read_csv(file_content_stream2)

## Subsetting the data for Payment and Spend variables
train = train[['customer_ID', 'P_2', 'P_3', 'P_4', 'S_3', 'S_5', 'S_6', 'S_7', 'S_8', 'S_9', 'S_11', 'S_12', 'S_13', 'S_15', 'S_16', 'S_17', 
               'S_18', 'S_19', 'S_20', 'S_22', 'S_23', 'S_24', 'S_25', 'S_26', 'S_27']]

## Appending target labels with train data-frame
train = train.merge(train_labels, on = 'customer_ID', how = 'left')

-- Process Starting --

In [ ]:
train.head()

In [ ]:
## Computing new Payment and Spend count features with the train data-frame
count_vars_train = train.groupby('customer_ID').agg({'P_3':['count'], 'S_3':['count'], 'S_7':['count'], 
                                                     'S_22': ['count'], 'S_23': ['count'], 'S_25': ['count']}).reset_index(drop = False)

## Editing the variable names in the data-frame
count_vars_train.columns = ['customer_ID', 'P_3_count', 'S_3_count', 'S_7_count', 'S_22_count', 'S_23_count', 'S_25_count']

# Creating binary count variables
count_vars_train['P_3_count_binary'] = np.where(count_vars_train["P_3_count"] > 0, 1, 0)
count_vars_train['S_3_count_binary'] = np.where(count_vars_train["S_3_count"] > 0, 1, 0)
count_vars_train['S_7_count_binary'] = np.where(count_vars_train["S_7_count"] > 0, 1, 0)
count_vars_train['S_22_count_binary'] = np.where(count_vars_train["S_22_count"] > 0, 1, 0)
count_vars_train['S_23_count_binary'] = np.where(count_vars_train["S_23_count"] > 0, 1, 0)
count_vars_train['S_25_count_binary'] = np.where(count_vars_train["S_25_count"] > 0, 1, 0)

## Sanity check
print('-- Training counts data-frame complete -- \n')

In [ ]:
## Imputing the train data-frame using the Mice Forest library

## Defining the input variables and dropping categorical variables
mf_train = train.drop(columns = ['customer_ID', 'target'])

# Building the miceforest kernel
kernel_train = mf.ImputationKernel(mf_train, datasets = 5, save_all_iterations = True)

## Assigning the final imputed data-frames
train_impute = kernel_train.complete_data(dataset = 0, inplace = False)

## Adding "customer_ID" back into the data-frames
train_impute = pd.concat([train[['customer_ID', 'target']], train_impute], axis = 1)

## Sanity check
print('-- Training data-frame imputation complete -- \n')

In [ ]:
## Creating other aggregated features using the imputed train data-frame

## Creating a series of aggregation functions
def data_range(x):
    return x.max() - x.min()
def iqr(x):
    return np.percentile(x, 75) - np.percentile(x, 25)
def avg_pct_change(x):
    return pd.Series(x.to_list()).pct_change().mean()
def correlation(x):
    return pd.Series(x.values).corr(other = pd.Series(x.index), method = 'pearson')

## Creating new Payment features with the cleaned train data-frame
payment_vars_train = train_impute.groupby('customer_ID').agg({'P_2':['mean', 'median', 'sum', data_range, iqr, avg_pct_change, correlation], 'P_3':['mean', 'median', 'sum', data_range, iqr, avg_pct_change, correlation], 'P_4':['mean', 'median', 'sum', data_range, iqr, avg_pct_change, correlation]}).reset_index(drop = False)

## Renaming variable names
payment_vars_train.columns = ['customer_ID', 'P_2_mean', 'P_2_median', 'P_2_sum', 'P_2_data_range', 'P_2_iqr', 'P_2_avg_pct_change', 'P_2_correlation', 'P_3_mean', 'P_3_median', 'P_3_sum', 'P_3_data_range', 'P_3_iqr', 'P_3_avg_pct_change', 'P_3_correlation', 'P_4_mean', 'P_4_median', 'P_4_sum', 'P_4_data_range', 'P_4_iqr', 'P_4_avg_pct_change', 'P_4_correlation']

## Creating new Spend features with the cleaned train data-frame
spend_vars_train = train_impute.groupby('customer_ID').agg({'S_3':['median', 'sum', data_range, iqr, avg_pct_change, correlation], 
                                                            'S_5':[data_range, iqr, avg_pct_change, correlation], 
                                                            'S_6':['mean', 'median', 'sum', 'mad', data_range, iqr, avg_pct_change, correlation], 
                                                            'S_8':['mean', 'median', 'sum', data_range, iqr, avg_pct_change, correlation], 
                                                            'S_13':['mean', 'sum', 'std', 'mad', data_range, iqr, avg_pct_change, correlation], 
                                                            'S_25':['mean', 'sum', 'std', 'mad', data_range, iqr, avg_pct_change, correlation], 
                                                            'S_27':[data_range, iqr, avg_pct_change, correlation]}).reset_index(drop = False)

spend_vars_train.columns = ['customer_ID', 'S_3_median', 'S_3_sum', 'S_3_data_range', 'S_3_iqr', 'S_3_avg_pct_change', 'S_3_correlation', 
                            'S_5_data_range', 'S_5_iqr', 'S_5_avg_pct_change', 'S_5_correlation', 
                            'S_6_mean', 'S_6_median', 'S_6_sum', 'S_6_mad', 'S_6_data_range', 'S_6_iqr', 'S_6_avg_pct_change', 'S_6_correlation', 
                            'S_8_mean', 'S_8_median', 'S_8_sum', 'S_8_data_range', 'S_8_iqr', 'S_8_avg_pct_change', 'S_8_correlation', 
                            'S_13_mean', 'S_13_sum', 'S_13_std', 'S_13_mad', 'S_13_data_range', 'S_13_iqr', 'S_13_avg_pct_change', 'S_13_correlation', 
                            'S_25_mean', 'S_25_sum', 'S_25_std', 'S_25_mad', 'S_25_data_range', 'S_25_iqr', 'S_25_avg_pct_change', 'S_25_correlation', 
                            'S_27_data_range', 'S_27_iqr', 'S_27_avg_pct_change', 'S_27_correlation']

## Sanity check
print('-- Training aggregations data-frame complete -- \n')

In [ ]:
spend_vars_train.columns = ['customer_ID', 'S_3_median', 'S_3_sum', 'S_3_data_range', 'S_3_iqr', 'S_3_avg_pct_change', 'S_3_correlation', 
                            'S_5_data_range', 'S_5_iqr', 'S_5_avg_pct_change', 'S_5_correlation', 
                            'S_6_mean', 'S_6_median', 'S_6_sum', 'S_6_mad', 'S_6_data_range', 'S_6_iqr', 'S_6_avg_pct_change', 'S_6_correlation', 
                            'S_8_mean', 'S_8_median', 'S_8_sum', 'S_8_data_range', 'S_8_iqr', 'S_8_avg_pct_change', 'S_8_correlation', 
                            'S_13_mean', 'S_13_sum', 'S_13_std', 'S_13_mad', 'S_13_data_range', 'S_13_iqr', 'S_13_avg_pct_change', 'S_13_correlation', 
                            'S_25_mean', 'S_25_sum', 'S_25_std', 'S_25_mad', 'S_25_data_range', 'S_25_iqr', 'S_25_avg_pct_change', 'S_25_correlation', 
                            'S_27_data_range', 'S_27_iqr', 'S_27_avg_pct_change', 'S_27_correlation']

In [ ]:
## Combining desired count features with other aggregated features to create final data-frame

## Joining the Payment and Spend train data-frames
training = payment_vars_train.merge(spend_vars_train, how = 'left', on = 'customer_ID')

## Joining the Training and Count data-frames
training = training.merge(count_vars_train, how = 'left', on = 'customer_ID')

## Appending target labels to training data-frame
training = training.merge(train_labels, on = 'customer_ID', how = 'left')

## -------------------------------------------

## Exporting the resulting training data-frame to a csv file
training.to_csv('amex_train_payment_spend.csv', index = False)

## Sanity check
print('-- Training data-frame complete -- \n')

In [1]:
## Importing libraries
import pandas as pd
import numpy as np
import miceforest as mf
from sklearn.feature_selection import RFECV
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import make_scorer
from Amex_Metric import amex_metric

In [2]:
new_train = pd.read_csv('/home/ec2-user/SageMaker/Analytics_Data_Science/American_Express/Evan/amex_train_payment_spend.csv')

new_train.head()

,customer_ID,P_2_mean,P_2_median,P_2_sum,P_2_data_range,P_2_iqr,P_2_avg_pct_change,P_2_correlation,P_3_mean,P_3_median,...,S_22_count,S_23_count,S_25_count,P_3_count_binary,S_3_count_binary,S_7_count_binary,S_22_count_binary,S_23_count_binary,S_25_count_binary,target
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.9336,0.9385,12.140,0.09180,0.012695,0.000233,-0.438767,0.6800,0.690,...,13,13,13,1,1,1,1,1,1,0
1,00000fd6641609c6ece5454664794f0340ad84dddce9a2...,0.9000,0.9050,11.695,0.06790,0.038086,-0.004342,-0.854416,0.5670,0.571,...,13,13,13,1,1,1,1,1,1,0
2,00001b22f846c82c51f6e3958ccd81970162bae8b007e8...,0.8784,0.8850,11.420,0.10645,0.027344,0.001643,-0.109422,0.6180,0.630,...,13,13,13,1,0,0,1,1,1,0
3,000041bdba6ecadd89a52d11886e8eaaec9325906c9723...,0.5990,0.5980,7.785,0.05615,0.033203,0.007730,0.953176,0.6110,0.623,...,13,13,13,1,1,1,1,1,1,0
4,00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...,0.8916,0.8794,11.590,0.13530,0.071289,-0.004811,-0.597527,0.5273,0.560,...,13,13,13,1,1,1,1,1,1,0

In [3]:
new_train.columns

Index(['customer_ID', 'P_2_mean', 'P_2_median', 'P_2_sum', 'P_2_data_range',
       'P_2_iqr', 'P_2_avg_pct_change', 'P_2_correlation', 'P_3_mean',
       'P_3_median', 'P_3_sum', 'P_3_data_range', 'P_3_iqr',
       'P_3_avg_pct_change', 'P_3_correlation', 'P_4_mean', 'P_4_median',
       'P_4_sum', 'P_4_data_range', 'P_4_iqr', 'P_4_avg_pct_change',
       'P_4_correlation', 'S_3_median', 'S_3_sum', 'S_3_data_range', 'S_3_iqr',
       'S_3_avg_pct_change', 'S_3_correlation', 'S_5_data_range', 'S_5_iqr',
       'S_5_avg_pct_change', 'S_5_correlation', 'S_6_mean', 'S_6_median',
       'S_6_sum', 'S_6_mad', 'S_6_data_range', 'S_6_iqr', 'S_6_avg_pct_change',
       'S_6_correlation', 'S_8_mean', 'S_8_median', 'S_8_sum',
       'S_8_data_range', 'S_8_iqr', 'S_8_avg_pct_change', 'S_8_correlation',
       'S_13_mean', 'S_13_sum', 'S_13_std', 'S_13_mad', 'S_13_data_range',
       'S_13_iqr', 'S_13_avg_pct_change', 'S_13_correlation', 'S_25_mean',
       'S_25_sum', 'S_25_std', 'S_25_mad', 'S_25_data_range', 'S_25_iqr',
       'S_25_avg_pct_change', 'S_25_correlation', 'S_27_data_range',
       'S_27_iqr', 'S_27_avg_pct_change', 'S_27_correlation', 'P_3_count',
       'S_3_count', 'S_7_count', 'S_22_count', 'S_23_count', 'S_25_count',
       'P_3_count_binary', 'S_3_count_binary', 'S_7_count_binary',
       'S_22_count_binary', 'S_23_count_binary', 'S_25_count_binary',
       'target'],
      dtype='object')

In [4]:
new_train.shape

(458913, 80)

In [5]:
new_train.dropna().shape

(452666, 80)

In [6]:
## Imputing the train data-frame using the Mice Forest library

## Defining the input variables and dropping categorical variables
mf_train = new_train.drop(columns = ['customer_ID', 'target'])

# Building the miceforest kernel
kernel_train = mf.ImputationKernel(mf_train, datasets = 5, save_all_iterations = True)

## Assigning the final imputed data-frames
train_impute = kernel_train.complete_data(dataset = 0, inplace = False)

## Adding "customer_ID" back into the data-frames
train_impute = pd.concat([new_train[['customer_ID', 'target']], train_impute], axis = 1)

## Sanity check
print('-- Training data-frame imputation complete -- \n')

-- Training data-frame imputation complete --

In [7]:
train_impute.shape

(458913, 80)

In [8]:
train_impute.dropna().shape

(458913, 80)

In [9]:
train_impute.head()

,customer_ID,target,P_2_mean,P_2_median,P_2_sum,P_2_data_range,P_2_iqr,P_2_avg_pct_change,P_2_correlation,P_3_mean,...,S_7_count,S_22_count,S_23_count,S_25_count,P_3_count_binary,S_3_count_binary,S_7_count_binary,S_22_count_binary,S_23_count_binary,S_25_count_binary
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0,0.9336,0.9385,12.140,0.09180,0.012695,0.000233,-0.438767,0.6800,...,13,13,13,13,1,1,1,1,1,1
1,00000fd6641609c6ece5454664794f0340ad84dddce9a2...,0,0.9000,0.9050,11.695,0.06790,0.038086,-0.004342,-0.854416,0.5670,...,13,13,13,13,1,1,1,1,1,1
2,00001b22f846c82c51f6e3958ccd81970162bae8b007e8...,0,0.8784,0.8850,11.420,0.10645,0.027344,0.001643,-0.109422,0.6180,...,0,13,13,13,1,0,0,1,1,1
3,000041bdba6ecadd89a52d11886e8eaaec9325906c9723...,0,0.5990,0.5980,7.785,0.05615,0.033203,0.007730,0.953176,0.6110,...,13,13,13,13,1,1,1,1,1,1
4,00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...,0,0.8916,0.8794,11.590,0.13530,0.071289,-0.004811,-0.597527,0.5273,...,4,13,13,13,1,1,1,1,1,1

In [10]:
ds = train_impute.isin([np.inf, -np.inf])
print(ds)

        customer_ID  target  P_2_mean  P_2_median  P_2_sum  P_2_data_range  \
0             False   False     False       False    False           False
1             False   False     False       False    False           False
2             False   False     False       False    False           False
3             False   False     False       False    False           False
4             False   False     False       False    False           False
...             ...     ...       ...         ...      ...             ...
458908        False   False     False       False    False           False
458909        False   False     False       False    False           False
458910        False   False     False       False    False           False
458911        False   False     False       False    False           False
458912        False   False     False       False    False           False

        P_2_iqr  P_2_avg_pct_change  P_2_correlation  P_3_mean  ...  \
0         False               False            False     False  ...
1         False               False            False     False  ...
2         False               False            False     False  ...
3         False               False            False     False  ...
4         False               False            False     False  ...
...         ...                 ...              ...       ...  ...
458908    False               False            False     False  ...
458909    False               False            False     False  ...
458910    False               False            False     False  ...
458911    False               False            False     False  ...
458912    False               False            False     False  ...

        S_7_count  S_22_count  S_23_count  S_25_count  P_3_count_binary  \
0           False       False       False       False             False
1           False       False       False       False             False
2           False       False       False       False             False
3           False       False       False       False             False
4           False       False       False       False             False
...           ...         ...         ...         ...               ...
458908      False       False       False       False             False
458909      False       False       False       False             False
458910      False       False       False       False             False
458911      False       False       False       False             False
458912      False       False       False       False             False

        S_3_count_binary  S_7_count_binary  S_22_count_binary  \
0                  False             False              False
1                  False             False              False
2                  False             False              False
3                  False             False              False
4                  False             False              False
...                  ...               ...                ...
458908             False             False              False
458909             False             False              False
458910             False             False              False
458911             False             False              False
458912             False             False              False

        S_23_count_binary  S_25_count_binary
0                   False              False
1                   False              False
2                   False              False
3                   False              False
4                   False              False
...                   ...                ...
458908              False              False
458909              False              False
458910              False              False
458911              False              False
458912              False              False

[458913 rows x 80 columns]

In [11]:
pd.DataFrame(ds.sum()).head()

             0
customer_ID  0
target       0
P_2_mean     0
P_2_median   0
P_2_sum      0

In [14]:
pd.set_option('display.max_columns', 200)

In [18]:
infs = train_impute[train_impute['P_4_avg_pct_change'] == np.inf].reset_index(drop = True)

infs.at[0, 'customer_ID']

'34d3033638417ca0501874529807ec33d02f9c165312a1d4c3fd4ce2c27c9358'

In [20]:
cust = train[train['customer_ID'] == '34d3033638417ca0501874529807ec33d02f9c165312a1d4c3fd4ce2c27c9358']
cust

,customer_ID,P_2,P_3,P_4,S_3,S_5,S_6,S_7,S_8,S_9,S_11,S_12,S_13,S_15,S_16,S_17,S_18,S_19,S_20,S_22,S_23,S_24,S_25,S_26,S_27,target
1144061,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.901367,0.636230,0.004677,0.098022,0.184814,0.008324,0.079651,0.755859,NaN,0.446777,0.415527,0.686035,0.208008,0.007851,0.105347,0.003662,0.008553,0.006248,0.973145,0.139771,0.985840,0.974121,0.536133,0.002132,0
1144062,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.870117,0.524414,0.004585,0.096985,0.191040,0.006817,0.074524,0.760254,NaN,0.407227,0.300049,0.686523,0.204224,0.001481,0.088806,0.008606,0.005966,0.005093,0.974609,0.135132,0.985352,0.975586,0.401367,0.006546,0
1144063,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.908691,0.659180,0.002687,0.067383,0.339355,0.000833,0.056549,0.753906,0.009148,0.561035,0.216309,0.847656,0.208496,0.002542,0.114075,0.003508,0.007671,0.004116,0.952637,0.140381,0.964355,0.976562,0.402344,0.285889,0
1144064,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.934570,0.659668,0.000884,0.080017,0.489502,0.000904,0.061676,1.003906,0.021606,0.446289,0.169922,0.679199,0.107361,0.009071,0.064880,0.007950,0.001854,0.002138,0.963867,0.138306,0.976074,0.973633,0.369873,0.257324,0
1144065,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.887695,0.544922,0.009720,0.097900,1.164062,0.006962,0.071106,0.760254,0.015732,0.447510,0.376465,0.680176,0.207153,0.003462,0.186523,0.007153,0.008743,0.003998,0.973145,0.137451,0.987305,0.975586,0.179443,0.280029,0
1144066,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.885742,0.549805,0.007942,0.099060,0.133301,0.005318,0.066711,0.761230,0.038757,0.447998,0.213013,0.681152,0.202148,0.002552,0.183228,1.008789,0.007412,0.000258,0.966309,0.133667,0.974609,0.975586,0.005173,0.288330,0
1144067,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.893066,0.602051,0.000332,0.101379,0.082703,0.004337,0.077393,0.759766,0.025543,0.403320,0.310303,0.682617,0.207275,0.005531,0.169556,1.008789,0.002956,0.001961,0.960449,0.130859,0.973633,0.978516,0.061523,0.311279,0
1144068,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.816406,0.585938,0.002821,0.113403,0.252930,0.005692,0.083191,0.761719,NaN,0.445068,0.349365,0.687988,0.201904,0.007156,0.009048,1.003906,0.006737,0.003983,0.964844,0.138428,0.980957,0.971191,0.143311,0.005104,0
1144069,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.791992,0.422852,0.003212,0.118225,0.361816,0.008842,0.078430,0.760742,NaN,0.485596,0.196655,0.686035,0.205078,0.009697,0.097290,0.004642,0.006889,0.006531,0.963379,0.135254,0.980469,0.972656,0.148804,0.000598,0
1144070,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.794922,0.416992,0.004395,0.119385,0.380615,0.009270,0.077209,0.752441,NaN,0.442139,0.248413,0.683105,0.206299,0.001660,0.285400,0.000546,0.003952,0.000485,0.966797,0.138306,0.980957,0.976074,0.149536,0.006016,0
1144071,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.791016,0.457275,0.002335,0.115479,0.391113,0.004375,0.080566,0.759766,NaN,0.565430,0.158691,0.851562,0.208374,0.005386,0.681641,0.005787,0.005669,0.006252,0.962891,0.140503,0.972656,0.969727,0.864258,0.005253,0
1144072,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.764648,0.471436,0.000000,0.124146,0.114319,0.004677,0.078369,0.758789,NaN,0.524902,0.199463,0.850586,0.202271,0.001950,0.642090,1.006836,0.001444,0.000978,0.959473,0.136597,0.978516,0.972656,0.916016,0.000345,0
1144073,34d3033638417ca0501874529807ec33d02f9c165312a1...,0.718750,0.430664,0.007504,0.127686,0.144043,0.000024,0.081909,0.760742,NaN,0.440186,0.133057,0.681641,0.204956,0.009781,0.505371,0.000351,0.008865,0.008652,0.960938,0.136230,0.976562,0.970215,1.086914,0.006779,0

In [29]:
def correlation(x):
    return pd.Series(x.values).corr(other = pd.Series(x.index), method = 'pearson')

def avg_pct_change(x):
    return pd.Series(x.to_list()).pct_change()[1:12].mean()

avg_pct_change(cust['P_4'])

1.2982680062894436

In [26]:
tester = avg_pct_change(cust['P_4'])[1:12]

In [28]:
tester.mean()

1.2982680062894436

In [ ]:
P_4_avg_pct_change, S_5_avg_pct_change, S_6_avg_pct_change, S_8_avg_pct_change, S_13_avg_pct_change, S_27_avg_pct_change

In [ ]:
## Defining the input and target variables
X = train_impute.drop(columns = ['customer_ID', 'target'])
Y = train_impute['target']

## Splitting the data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y)

## Defining the customized scoring function 
amex_function = make_scorer(amex_metric, greater_is_better = True, needs_proba = True)

## Defining empty list to store results
features_to_select = list()

## Repeating steps 100 times:
for i in range(0, 5):
    
    ## Runing RFECV with Random Forest as a base algorithm
    rf_rfecv = RFECV(estimator = RandomForestClassifier(n_estimators = 300, max_depth = 3), step = 1, scoring = amex_function, 
                     min_features_to_select = 5, cv = 3).fit(X_train, Y_train)
    
    ## Appending results 
    features_to_select.append(X_train.columns[rf_rfecv.support_])
    
## Putting results as data-frame
features_to_select = pd.DataFrame(features_to_select)

features_to_select.to_csv('feature_selection_results.csv', index = False)

## Sanity check
print('-- Completed --')