In [ ]:
## Importing libraries
import boto3
import pandas as pd
import numpy as np
from random import sample
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.impute import KNNImputer
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
pd.set_option('display.max_columns', 200)


## Defining the bucket
s3 = boto3.resource('s3')
bucket_name = 'evan-callaghan-bucket'
bucket = s3.Bucket(bucket_name)

file_key = 'Kaggle-American-Express-Default/amex_sample_submission.csv'
file_key2 = 'Kaggle-American-Express-Default/amex_train_labels.csv'
file_key3 = 'Kaggle-American-Express-Default/amex_train_data.csv'
file_key4 = 'Kaggle-American-Express-Default/amex_test_data.csv'

bucket_object = bucket.Object(file_key)
bucket_object2 = bucket.Object(file_key2)
bucket_object3 = bucket.Object(file_key3)
bucket_object4 = bucket.Object(file_key4)

file_object = bucket_object.get()
file_object2 = bucket_object2.get()
file_object3 = bucket_object3.get()
file_object4 = bucket_object4.get()

file_content_stream = file_object.get('Body')
file_content_stream2 = file_object2.get('Body')
file_content_stream3 = file_object3.get('Body')
file_content_stream4 = file_object4.get('Body')

## Creating data-type dictionary for reading the train data-frame
dtype_dict = {'customer_ID': "object", 'S_2': "object", 'P_2': 'float16', 'D_39': 'float16', 'B_1': 'float16','B_2': 'float16',
              'R_1': 'float16','S_3': 'float16','D_41': 'float16','B_3': 'float16','D_42': 'float16','D_43': 'float16','D_44': 'float16',
              'B_4': 'float16','D_45': 'float16','B_5': 'float16','R_2': 'float16','D_46': 'float16','D_47': 'float16','D_48': 'float16',
              'D_49': 'float16','B_6': 'float16','B_7': 'float16','B_8': 'float16','D_50': 'float16','D_51': 'float16','B_9': 'float16',
              'R_3': 'float16','D_52': 'float16','P_3': 'float16','B_10': 'float16','D_53': 'float16','S_5': 'float16','B_11': 'float16',
              'S_6': 'float16','D_54': 'float16','R_4': 'float16','S_7': 'float16','B_12': 'float16','S_8': 'float16','D_55': 'float16',
              'D_56': 'float16','B_13': 'float16','R_5': 'float16','D_58': 'float16','S_9': 'float16','B_14': 'float16','D_59': 'float16',
              'D_60': 'float16','D_61': 'float16','B_15': 'float16','S_11': 'float16','D_62': 'float16','D_63': 'object','D_64': 'object',
              'D_65': 'float16','B_16': 'float16','B_17': 'float16','B_18': 'float16','B_19': 'float16','D_66': 'float16','B_20': 'float16',
              'D_68': 'float16','S_12': 'float16','R_6': 'float16','S_13': 'float16','B_21': 'float16','D_69': 'float16','B_22': 'float16',
              'D_70': 'float16','D_71': 'float16','D_72': 'float16','S_15': 'float16','B_23': 'float16','D_73': 'float16','P_4': 'float16',
              'D_74': 'float16','D_75': 'float16','D_76': 'float16','B_24': 'float16','R_7': 'float16','D_77': 'float16','B_25': 'float16',
              'B_26': 'float16','D_78': 'float16','D_79': 'float16','R_8': 'float16','R_9': 'float16','S_16': 'float16','D_80': 'float16',
              'R_10': 'float16','R_11': 'float16','B_27': 'float16','D_81': 'float16','D_82': 'float16','S_17': 'float16','R_12': 'float16',
              'B_28': 'float16','R_13': 'float16','D_83': 'float16','R_14': 'float16','R_15': 'float16','D_84': 'float16','R_16': 'float16',
              'B_29': 'float16','B_30': 'float16','S_18': 'float16','D_86': 'float16','D_87': 'float16','R_17': 'float16','R_18': 'float16',
              'D_88': 'float16','B_31': 'int64','S_19': 'float16','R_19': 'float16','B_32': 'float16','S_20': 'float16','R_20': 'float16',
              'R_21': 'float16','B_33': 'float16','D_89': 'float16','R_22': 'float16','R_23': 'float16','D_91': 'float16','D_92': 'float16',
              'D_93': 'float16','D_94': 'float16','R_24': 'float16','R_25': 'float16','D_96': 'float16','S_22': 'float16','S_23': 'float16',
              'S_24': 'float16','S_25': 'float16','S_26': 'float16','D_102': 'float16','D_103': 'float16','D_104': 'float16','D_105': 'float16',
              'D_106': 'float16','D_107': 'float16','B_36': 'float16','B_37': 'float16', 'R_26': 'float16','R_27': 'float16','B_38': 'float16',
              'D_108': 'float16','D_109': 'float16','D_110': 'float16','D_111': 'float16','B_39': 'float16','D_112': 'float16','B_40': 'float16',
              'S_27': 'float16','D_113': 'float16','D_114': 'float16','D_115': 'float16','D_116': 'float16','D_117': 'float16','D_118': 'float16',
              'D_119': 'float16','D_120': 'float16','D_121': 'float16','D_122': 'float16','D_123': 'float16','D_124': 'float16','D_125': 'float16',
              'D_126': 'float16','D_127': 'float16','D_128': 'float16','D_129': 'float16','B_41': 'float16','B_42': 'float16','D_130': 'float16',
              'D_131': 'float16','D_132': 'float16','D_133': 'float16','R_28': 'float16','D_134': 'float16','D_135': 'float16','D_136': 'float16',
              'D_137': 'float16','D_138': 'float16','D_139': 'float16','D_140': 'float16','D_141': 'float16','D_142': 'float16','D_143': 'float16',
              'D_144': 'float16','D_145': 'float16'}

## Reading the data
sample_submission = pd.read_csv(file_content_stream)
train_labels = pd.read_csv(file_content_stream2)
train = pd.read_csv(file_content_stream3, dtype = dtype_dict)
test = pd.read_csv(file_content_stream4, dtype = dtype_dict)

Matplotlib is building the font cache; this may take a moment.

In [ ]:
train.shape

In [ ]:
missing = pd.DataFrame(train.isnull().sum()).T
missing

In [ ]:
test.shape

In [ ]:
missing = pd.DataFrame(test.isnull().sum()).T
missing

In [16]:
pip install miceforest

Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
Requirement already satisfied: miceforest in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (5.4.0)
Requirement already satisfied: blosc in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from miceforest) (1.10.6)
Requirement already satisfied: lightgbm>=3.3.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from miceforest) (3.3.2)
Requirement already satisfied: numpy in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from miceforest) (1.20.3)
Requirement already satisfied: dill in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from miceforest) (0.3.4)
Requirement already satisfied: wheel in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from lightgbm>=3.3.1->miceforest) (0.37.0)
Requirement already satisfied: scikit-learn!=0.22.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from lightgbm>=3.3.1->miceforest) (1.0.1)
Requirement already satisfied: scipy in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from lightgbm>=3.3.1->miceforest) (1.5.3)
Requirement already satisfied: joblib>=0.11 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from scikit-learn!=0.22.0->lightgbm>=3.3.1->miceforest) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.8/site-packages (from scikit-learn!=0.22.0->lightgbm>=3.3.1->miceforest) (3.0.0)
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/home/ec2-user/anaconda3/envs/python3/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [17]:
## Importing libraries
import boto3
import pandas as pd
import numpy as np
import miceforest as mf
from sklearn.impute import KNNImputer
from random import sample

## Defining the bucket
s3 = boto3.resource('s3')
bucket_name = 'evan-callaghan-bucket'
bucket = s3.Bucket(bucket_name)

file_key = 'Kaggle-American-Express-Default/amex_train_data.csv'
file_key2 = 'Kaggle-American-Express-Default/amex_test_data.csv'

bucket_object = bucket.Object(file_key)
bucket_object2 = bucket.Object(file_key2)

file_object = bucket_object.get()
file_object2 = bucket_object2.get()

file_content_stream = file_object.get('Body')
file_content_stream2 = file_object2.get('Body')

## Creating data-type dictionary for reading the train data-frame
dtype_dict = {'customer_ID': "object", 'S_2': "object", 'P_2': 'float16', 'D_39': 'float16', 'B_1': 'float16','B_2': 'float16', 'R_1': 'float16','S_3': 'float16','D_41': 'float16','B_3': 'float16','D_42': 'float16','D_43': 'float16','D_44': 'float16', 'B_4': 'float16','D_45': 'float16','B_5': 'float16','R_2': 'float16','D_46': 'float16','D_47': 'float16','D_48': 'float16', 'D_49': 'float16','B_6': 'float16','B_7': 'float16','B_8': 'float16','D_50': 'float16','D_51': 'float16','B_9': 'float16', 'R_3': 'float16','D_52': 'float16','P_3': 'float16','B_10': 'float16','D_53': 'float16','S_5': 'float16','B_11': 'float16', 'S_6': 'float16','D_54': 'float16','R_4': 'float16','S_7': 'float16','B_12': 'float16','S_8': 'float16','D_55': 'float16', 'D_56': 'float16','B_13': 'float16','R_5': 'float16','D_58': 'float16','S_9': 'float16','B_14': 'float16','D_59': 'float16', 'D_60': 'float16','D_61': 'float16','B_15': 'float16','S_11': 'float16','D_62': 'float16','D_63': 'object','D_64': 'object', 'D_65': 'float16','B_16': 'float16','B_17': 'float16','B_18': 'float16','B_19': 'float16','D_66': 'float16','B_20': 'float16', 'D_68': 'float16','S_12': 'float16','R_6': 'float16','S_13': 'float16','B_21': 'float16','D_69': 'float16','B_22': 'float16', 'D_70': 'float16','D_71': 'float16','D_72': 'float16','S_15': 'float16','B_23': 'float16','D_73': 'float16','P_4': 'float16', 'D_74': 'float16','D_75': 'float16','D_76': 'float16','B_24': 'float16','R_7': 'float16','D_77': 'float16','B_25': 'float16', 'B_26': 'float16','D_78': 'float16','D_79': 'float16','R_8': 'float16','R_9': 'float16','S_16': 'float16','D_80': 'float16', 'R_10': 'float16','R_11': 'float16','B_27': 'float16','D_81': 'float16','D_82': 'float16','S_17': 'float16','R_12': 'float16', 'B_28': 'float16','R_13': 'float16','D_83': 'float16','R_14': 'float16','R_15': 'float16','D_84': 'float16','R_16': 'float16', 'B_29': 'float16','B_30': 'float16','S_18': 'float16','D_86': 'float16','D_87': 'float16','R_17': 'float16','R_18': 'float16', 'D_88': 'float16','B_31': 'int64','S_19': 'float16','R_19': 'float16','B_32': 'float16','S_20': 'float16','R_20': 'float16', 'R_21': 'float16','B_33': 'float16','D_89': 'float16','R_22': 'float16','R_23': 'float16','D_91': 'float16','D_92': 'float16', 'D_93': 'float16','D_94': 'float16','R_24': 'float16','R_25': 'float16','D_96': 'float16','S_22': 'float16','S_23': 'float16', 'S_24': 'float16','S_25': 'float16','S_26': 'float16','D_102': 'float16','D_103': 'float16','D_104': 'float16','D_105': 'float16', 'D_106': 'float16','D_107': 'float16','B_36': 'float16','B_37': 'float16', 'R_26': 'float16','R_27': 'float16','B_38': 'float16', 'D_108': 'float16','D_109': 'float16','D_110': 'float16','D_111': 'float16','B_39': 'float16','D_112': 'float16','B_40': 'float16', 'S_27': 'float16','D_113': 'float16','D_114': 'float16','D_115': 'float16','D_116': 'float16','D_117': 'float16','D_118': 'float16', 'D_119': 'float16','D_120': 'float16','D_121': 'float16','D_122': 'float16','D_123': 'float16','D_124': 'float16','D_125': 'float16', 'D_126': 'float16','D_127': 'float16','D_128': 'float16','D_129': 'float16','B_41': 'float16','B_42': 'float16','D_130': 'float16', 'D_131': 'float16','D_132': 'float16','D_133': 'float16','R_28': 'float16','D_134': 'float16','D_135': 'float16','D_136': 'float16', 'D_137': 'float16','D_138': 'float16','D_139': 'float16','D_140': 'float16','D_141': 'float16','D_142': 'float16','D_143': 'float16', 'D_144': 'float16','D_145': 'float16'}

## Reading the data
train = pd.read_csv(file_content_stream, dtype = dtype_dict)

In [18]:
## Builidng a subset of the training data-frame with 1000 randomly sampled customers
listy = set(train['customer_ID'].unique())
samples = sample(listy, 1000)

## Subsetting the data
train_sample = train[np.isin(train['customer_ID'], samples)]

## Printing the shape of the resulting data-frame
print(train_sample.shape)
print(train_sample.isnull().sum(0))

(12015, 190)
customer_ID        0
S_2                0
P_2              102
D_39               0
B_1                0
               ...
D_141            218
D_142          10112
D_143            218
D_144            100
D_145            218
Length: 190, dtype: int64

In [19]:
train_sample_impute = train_sample.drop(columns = ['customer_ID', 'S_2', 'D_63', 'D_64'])

In [28]:
# Create kernel. 
kernel = mf.ImputationKernel(train_sample_impute, datasets = 5, save_all_iterations = True)

# Run the MICE algorithm for 2 iterations on each of the datasets
#kernel.mice(1)

# Printing the kernel will show you some high level information.
print(kernel)

train_sample_cleaned = kernel.complete_data(dataset = 0, inplace = False)
print(train_sample_cleaned.isnull().sum(0))

              Class: ImputationKernel
           Datasets: 5
         Iterations: 0
  Imputed Variables: 116
save_all_iterations: True
P_2      0
D_39     0
B_1      0
B_2      0
R_1      0
        ..
D_141    0
D_142    0
D_143    0
D_144    0
D_145    0
Length: 186, dtype: int64

In [29]:
train_sample_impute.head()

,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,D_42,D_43,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
14290,0.998535,0.000418,0.010109,0.818848,0.008186,0.088562,0.002455,0.010719,NaN,0.046783,...,NaN,NaN,NaN,0.005848,0.006378,0.004738,NaN,0.000621,0.000418,0.007076
14291,0.996582,0.002264,0.013962,0.810059,0.002098,0.087097,0.004692,0.008636,NaN,0.051208,...,NaN,NaN,NaN,0.000520,0.003052,0.000707,NaN,0.008720,0.003944,0.000738
14292,0.996094,0.005371,0.096680,0.818848,0.006207,0.113464,0.001745,0.012527,NaN,0.049744,...,NaN,NaN,NaN,0.004005,0.005924,0.003897,NaN,0.003880,0.001280,0.009827
14293,1.001953,0.007336,0.007927,1.000977,0.007011,0.116638,0.009468,0.011299,NaN,0.033600,...,NaN,NaN,NaN,0.002110,0.002956,0.006790,NaN,0.003960,0.000989,0.005611
14294,0.995605,0.007420,0.008789,1.009766,0.002340,0.112610,0.002287,0.009514,NaN,0.031616,...,NaN,NaN,NaN,0.005013,0.003735,0.005825,NaN,0.000808,0.009758,0.006134

In [30]:
train_sample_cleaned.head()

,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,D_42,D_43,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
14290,0.998535,0.000418,0.010109,0.818848,0.008186,0.088562,0.002455,0.010719,0.548828,0.046783,...,0.257080,0.008453,0.509277,0.005848,0.006378,0.004738,0.468750,0.000621,0.000418,0.007076
14291,0.996582,0.002264,0.013962,0.810059,0.002098,0.087097,0.004692,0.008636,0.400146,0.051208,...,0.002161,0.008492,0.501953,0.000520,0.003052,0.000707,0.545898,0.008720,0.003944,0.000738
14292,0.996094,0.005371,0.096680,0.818848,0.006207,0.113464,0.001745,0.012527,0.022095,0.049744,...,0.000285,0.006264,0.506348,0.004005,0.005924,0.003897,1.272461,0.003880,0.001280,0.009827
14293,1.001953,0.007336,0.007927,1.000977,0.007011,0.116638,0.009468,0.011299,0.096802,0.033600,...,0.251709,0.003504,0.002880,0.002110,0.002956,0.006790,0.702148,0.003960,0.000989,0.005611
14294,0.995605,0.007420,0.008789,1.009766,0.002340,0.112610,0.002287,0.009514,0.251465,0.031616,...,0.503906,0.007313,0.001687,0.005013,0.003735,0.005825,0.535645,0.000808,0.009758,0.006134